
import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ru' | 'uk' | 'de' | 'ja' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'title': 'Minecraft Java Finder',
    'subtitle': 'Find the perfect Java version for your Minecraft setup. Compatible with all versions, modloaders, and operating systems. AI assistant included.',
    'javaSearch': 'Java Search',
    'launchers': 'Launchers',
    'developer': 'Developer',
    'minecraftVersion': 'Minecraft Version',
    'framework': 'Framework/Modloader',
    'operatingSystem': 'Operating System',
    'detected': 'Detected',
    'findJavaVersion': 'Find Java Version',
    'recommendedJava': 'Recommended Java Version',
    'recommended': 'Recommended',
    'primaryDownload': 'Primary Download Source',
    'showAlternatives': 'Show Alternative Sources',
    'installInstructions': 'Installation Instructions for',
    'autoCheck': 'Auto-Check Compatibility',
    'checkCompatibility': 'Check My System',
    'compatible': 'Compatible',
    'incompatible': 'Incompatible',
    'aboutCreator': 'About the Creator',
    'projectInfo': 'Project Information',
    'siteInfo': 'Site Information',
    'version': 'Version',
    'lastUpdate': 'Last Update',
    'theme': 'Theme',
    'language': 'Language',
    'light': 'Light',
    'dark': 'Dark',
    'system': 'System',
    'aiDescription': 'Ask questions about Java, Minecraft, mods and get personalized recommendations from AI. Now with voice and image support!',
    'apiKeySetup': 'API Key Setup',
    'apiKeyDescription': 'For AI to work, you need to set up the VITE_GEMINI_API_KEY environment variable in project settings. Get your key at',
    'startConversation': 'Start conversation with AI',
    'exampleQuestions': 'Example questions: "What Java version is needed for Minecraft 1.19.2 with Forge?", "Help me set up OptiFine", "Why won\'t my mod start?"',
    'askQuestion': 'Ask a question about Java or Minecraft...',
    'enterToSend': 'Press Enter to send, Shift+Enter for new line',
    'sending': 'Sending...',
    'send': 'Send',
    'error': 'Error',
    'aiError': 'Failed to get AI response. Check API connection.',
    'microphoneError': 'Failed to access microphone. Please check permissions.',
    'checkingCompatibility': 'Checking compatibility...',
    'compatibilityError': 'Failed to check compatibility',
    'selectVersion': 'Select a version',
    'selectFramework': 'Select framework',
    'selectOS': 'Select operating system',
    'installGuide': 'Installation Guide',
    'downloadJava': 'Download Java',
    'alternativeSources': 'Alternative Sources',
    'hideAlternatives': 'Hide Alternatives',
    'loading': 'Loading...',
    'tryAgain': 'Try Again'
  },
  ru: {
    'title': 'Поиск Java для Minecraft',
    'subtitle': 'Найдите идеальную версию Java для вашей установки Minecraft. Совместимо со всеми версиями, модлоадерами и операционными системами. Включен AI помощник.',
    'javaSearch': 'Поиск Java',
    'launchers': 'Лаунчеры',
    'developer': 'Разработчик',
    'minecraftVersion': 'Версия Minecraft',
    'framework': 'Фреймворк/Модлоадер',
    'operatingSystem': 'Операционная система',
    'detected': 'Обнаружено',
    'findJavaVersion': 'Найти версию Java',
    'recommendedJava': 'Рекомендуемая версия Java',
    'recommended': 'Рекомендуется',
    'primaryDownload': 'Основной источник загрузки',
    'showAlternatives': 'Показать альтернативные источники',
    'installInstructions': 'Инструкции по установке для',
    'autoCheck': 'Авто-проверка совместимости',
    'checkCompatibility': 'Проверить мою систему',
    'compatible': 'Совместимо',
    'incompatible': 'Несовместимо',
    'aboutCreator': 'О создателе',
    'projectInfo': 'Информация о проекте',
    'siteInfo': 'Информация о сайте',
    'version': 'Версия',
    'lastUpdate': 'Последнее обновление',
    'theme': 'Тема',
    'language': 'Язык',
    'light': 'Светлая',
    'dark': 'Тёмная',
    'system': 'Системная',
    'aiDescription': 'Задавайте вопросы о Java, Minecraft, модах и получайте персонализированные рекомендации от ИИ. Теперь с поддержкой голоса и изображений!',
    'apiKeySetup': 'Настройка API ключа',
    'apiKeyDescription': 'Для работы AI необходимо настроить переменную окружения VITE_GEMINI_API_KEY в настройках проекта. Получите ключ в',
    'startConversation': 'Начните разговор с AI',
    'exampleQuestions': 'Примеры вопросов: "Какая версия Java нужна для Minecraft 1.19.2 с Forge?", "Помогите настроить OptiFine", "Почему не запускается мод?"',
    'askQuestion': 'Задайте вопрос о Java или Minecraft...',
    'enterToSend': 'Нажмите Enter для отправки, Shift+Enter для новой строки',
    'sending': 'Отправка...',
    'send': 'Отправить',
    'error': 'Ошибка',
    'aiError': 'Не удалось получить ответ от AI. Проверьте подключение к API.',
    'microphoneError': 'Не удалось получить доступ к микрофону. Проверьте разрешения.',
    'checkingCompatibility': 'Проверка совместимости...',
    'compatibilityError': 'Не удалось проверить совместимость',
    'selectVersion': 'Выберите версию',
    'selectFramework': 'Выберите фреймворк',
    'selectOS': 'Выберите операционную систему',
    'installGuide': 'Руководство по установке',
    'downloadJava': 'Скачать Java',
    'alternativeSources': 'Альтернативные источники',
    'hideAlternatives': 'Скрыть альтернативы',
    'loading': 'Загрузка...',
    'tryAgain': 'Попробовать снова'
  },
  uk: {
    'title': 'Пошук Java для Minecraft',
    'subtitle': 'Знайдіть ідеальну версію Java для вашої установки Minecraft. Сумісний з усіма версіями, модлоадерами та операційними системами. Включено AI помічник.',
    'javaSearch': 'Пошук Java',
    'launchers': 'Лаунчери',
    'developer': 'Розробник',
    'minecraftVersion': 'Версія Minecraft',
    'framework': 'Фреймворк/Модлоадер',
    'operatingSystem': 'Операційна система',
    'detected': 'Виявлено',
    'findJavaVersion': 'Знайти версію Java',
    'recommendedJava': 'Рекомендована версія Java',
    'recommended': 'Рекомендується',
    'primaryDownload': 'Основне джерело завантаження',
    'showAlternatives': 'Показати альтернативні джерела',
    'installInstructions': 'Інструкції з встановлення для',
    'autoCheck': 'Авто-перевірка сумісності',
    'checkCompatibility': 'Перевірити мою систему',
    'compatible': 'Сумісно',
    'incompatible': 'Несумісно',
    'aboutCreator': 'Про створювача',
    'projectInfo': 'Інформація про проект',
    'siteInfo': 'Інформація про сайт',
    'version': 'Версія',
    'lastUpdate': 'Останнє оновлення',
    'theme': 'Тема',
    'language': 'Мова',
    'light': 'Світла',
    'dark': 'Темна',
    'system': 'Системна',
    'aiDescription': 'Ставте питання про Java, Minecraft, моди та отримуйте персоналізовані рекомендації від ШІ. Тепер з підтримкою голосу та зображень!',
    'apiKeySetup': 'Налаштування API ключа',
    'apiKeyDescription': 'Для роботи AI необхідно налаштувати змінну оточення VITE_GEMINI_API_KEY у налаштуваннях проекту. Отримайте ключ у',
    'startConversation': 'Почніть розмову з AI',
    'exampleQuestions': 'Приклади питань: "Яка версія Java потрібна для Minecraft 1.19.2 з Forge?", "Допоможіть налаштувати OptiFine", "Чому не запускається мод?"',
    'askQuestion': 'Поставте питання про Java або Minecraft...',
    'enterToSend': 'Натисніть Enter для відправки, Shift+Enter для нового рядка',
    'sending': 'Відправка...',
    'send': 'Відправити',
    'error': 'Помилка',
    'aiError': 'Не вдалося отримати відповідь від AI. Перевірте підключення до API.',
    'microphoneError': 'Не вдалося отримати доступ до мікрофона. Перевірте дозволи.',
    'checkingCompatibility': 'Перевірка сумісності...',
    'compatibilityError': 'Не вдалося перевірити сумісність',
    'selectVersion': 'Оберіть версію',
    'selectFramework': 'Оберіть фреймворк',
    'selectOS': 'Оберіть операційну систему',
    'installGuide': 'Посібник з встановлення',
    'downloadJava': 'Завантажити Java',
    'alternativeSources': 'Альтернативні джерела',
    'hideAlternatives': 'Приховати альтернативи',
    'loading': 'Завантаження...',
    'tryAgain': 'Спробувати знову'
  },
  de: {
    'title': 'Minecraft Java Finder',
    'subtitle': 'Finden Sie die perfekte Java-Version für Ihr Minecraft-Setup. Kompatibel mit allen Versionen, Modladern und Betriebssystemen. AI-Assistent inklusive.',
    'javaSearch': 'Java Suche',
    'launchers': 'Launcher',
    'developer': 'Entwickler',
    'minecraftVersion': 'Minecraft Version',
    'framework': 'Framework/Modlader',
    'operatingSystem': 'Betriebssystem',
    'detected': 'Erkannt',
    'findJavaVersion': 'Java Version finden',
    'recommendedJava': 'Empfohlene Java Version',
    'recommended': 'Empfohlen',
    'primaryDownload': 'Primäre Download-Quelle',
    'showAlternatives': 'Alternative Quellen anzeigen',
    'installInstructions': 'Installationsanweisungen für',
    'autoCheck': 'Auto-Kompatibilitätsprüfung',
    'checkCompatibility': 'Mein System prüfen',
    'compatible': 'Kompatibel',
    'incompatible': 'Inkompatibel',
    'aboutCreator': 'Über den Ersteller',
    'projectInfo': 'Projektinformationen',
    'siteInfo': 'Site-Informationen',
    'version': 'Version',
    'lastUpdate': 'Letztes Update',
    'theme': 'Design',
    'language': 'Sprache',
    'light': 'Hell',
    'dark': 'Dunkel',
    'system': 'System',
    'aiDescription': 'Stellen Sie Fragen zu Java, Minecraft, Mods und erhalten Sie personalisierte Empfehlungen von der KI. Jetzt mit Sprach- und Bildunterstützung!',
    'apiKeySetup': 'API-Schlüssel Einrichtung',
    'apiKeyDescription': 'Damit die KI funktioniert, müssen Sie die Umgebungsvariable VITE_GEMINI_API_KEY in den Projekteinstellungen einrichten. Holen Sie sich Ihren Schlüssel bei',
    'startConversation': 'Gespräch mit KI beginnen',
    'exampleQuestions': 'Beispielfragen: "Welche Java-Version wird für Minecraft 1.19.2 mit Forge benötigt?", "Helfen Sie mir beim Einrichten von OptiFine", "Warum startet mein Mod nicht?"',
    'askQuestion': 'Stellen Sie eine Frage zu Java oder Minecraft...',
    'enterToSend': 'Enter zum Senden drücken, Shift+Enter für neue Zeile',
    'sending': 'Senden...',
    'send': 'Senden',
    'error': 'Fehler',
    'aiError': 'KI-Antwort konnte nicht abgerufen werden. Überprüfen Sie die API-Verbindung.',
    'microphoneError': 'Zugriff auf Mikrofon fehlgeschlagen. Bitte überprüfen Sie die Berechtigungen.',
    'checkingCompatibility': 'Kompatibilität prüfen...',
    'compatibilityError': 'Kompatibilität konnte nicht überprüft werden',
    'selectVersion': 'Version auswählen',
    'selectFramework': 'Framework auswählen',
    'selectOS': 'Betriebssystem auswählen',
    'installGuide': 'Installationsanleitung',
    'downloadJava': 'Java herunterladen',
    'alternativeSources': 'Alternative Quellen',
    'hideAlternatives': 'Alternativen ausblenden',
    'loading': 'Laden...',
    'tryAgain': 'Erneut versuchen'
  },
  ja: {
    'title': 'Minecraft Java検索',
    'subtitle': 'MinecraftセットアップのためのJavaバージョンを見つけます。すべてのバージョン、モッドローダー、オペレーティングシステムと互換性があります。AIアシスタント付き。',
    'javaSearch': 'Java検索',
    'launchers': 'ランチャー',
    'developer': '開発者',
    'minecraftVersion': 'Minecraftバージョン',
    'framework': 'フレームワーク/モッドローダー',
    'operatingSystem': 'オペレーティングシステム',
    'detected': '検出済み',
    'findJavaVersion': 'Javaバージョンを見つける',
    'recommendedJava': '推奨Javaバージョン',
    'recommended': '推奨',
    'primaryDownload': 'メインダウンロードソース',
    'showAlternatives': '代替ソースを表示',
    'installInstructions': 'インストール手順',
    'autoCheck': '自動互換性チェック',
    'checkCompatibility': 'システムをチェック',
    'compatible': '互換性あり',
    'incompatible': '互換性なし',
    'aboutCreator': '作成者について',
    'projectInfo': 'プロジェクト情報',
    'siteInfo': 'サイト情報',
    'version': 'バージョン',
    'lastUpdate': '最終更新',
    'theme': 'テーマ',
    'language': '言語',
    'light': 'ライト',
    'dark': 'ダーク',
    'system': 'システム',
    'aiDescription': 'Java、Minecraft、モッドについて質問し、AIからパーソナライズされた推奨事項を取得します。音声と画像のサポート付き！',
    'apiKeySetup': 'APIキー設定',
    'apiKeyDescription': 'AIが機能するには、プロジェクト設定でVITE_GEMINI_API_KEY環境変数を設定する必要があります。キーを取得する場所',
    'startConversation': 'AIとの会話を開始',
    'exampleQuestions': '質問例：「Minecraft 1.19.2 with ForgeにはどのJavaバージョンが必要ですか？」「OptiFineのセットアップを手伝って」「なぜ私のModが起動しないのですか？」',
    'askQuestion': 'JavaまたはMinecraftについて質問してください...',
    'enterToSend': 'Enterで送信、Shift+Enterで改行',
    'sending': '送信中...',
    'send': '送信',
    'error': 'エラー',
    'aiError': 'AI応答を取得できませんでした。API接続を確認してください。',
    'microphoneError': 'マイクへのアクセスに失敗しました。権限を確認してください。',
    'checkingCompatibility': '互換性を確認中...',
    'compatibilityError': '互換性を確認できませんでした',
    'selectVersion': 'バージョンを選択',
    'selectFramework': 'フレームワークを選択',
    'selectOS': 'オペレーティングシステムを選択',
    'installGuide': 'インストールガイド',
    'downloadJava': 'Javaをダウンロード',
    'alternativeSources': '代替ソース',
    'hideAlternatives': '代替を隠す',
    'loading': '読み込み中...',
    'tryAgain': '再試行'
  },
  zh: {
    'title': 'Minecraft Java 查找器',
    'subtitle': '为您的 Minecraft 设置找到完美的 Java 版本。兼容所有版本、模组加载器和操作系统。包含AI助手。',
    'javaSearch': 'Java 搜索',
    'launchers': '启动器',
    'developer': '开发者',
    'minecraftVersion': 'Minecraft 版本',
    'framework': '框架/模组加载器',
    'operatingSystem': '操作系统',
    'detected': '已检测',
    'findJavaVersion': '查找 Java 版本',
    'recommendedJava': '推荐的 Java 版本',
    'recommended': '推荐',
    'primaryDownload': '主要下载源',
    'showAlternatives': '显示替代源',
    'installInstructions': '安装说明',
    'autoCheck': '自动兼容性检查',
    'checkCompatibility': '检查我的系统',
    'compatible': '兼容',
    'incompatible': '不兼容',
    'aboutCreator': '关于创建者',
    'projectInfo': '项目信息',
    'siteInfo': '网站信息',
    'version': '版本',
    'lastUpdate': '最后更新',
    'theme': '主题',
    'language': '语言',
    'light': '亮色',
    'dark': '暗色',
    'system': '系统',
    'aiDescription': '询问有关Java、Minecraft、模组的问题，并从AI获得个性化建议。现在支持语音和图像！',
    'apiKeySetup': 'API密钥设置',
    'apiKeyDescription': '为了使AI工作，您需要在项目设置中设置VITE_GEMINI_API_KEY环境变量。在此处获取您的密钥',
    'startConversation': '开始与AI对话',
    'exampleQuestions': '示例问题："Minecraft 1.19.2 with Forge需要什么Java版本？"，"帮我设置OptiFine"，"为什么我的模组无法启动？"',
    'askQuestion': '询问有关Java或Minecraft的问题...',
    'enterToSend': '按Enter发送，Shift+Enter换行',
    'sending': '发送中...',
    'send': '发送',
    'error': '错误',
    'aiError': '无法获取AI响应。请检查API连接。',
    'microphoneError': '无法访问麦克风。请检查权限。',
    'checkingCompatibility': '检查兼容性中...',
    'compatibilityError': '无法检查兼容性',
    'selectVersion': '选择版本',
    'selectFramework': '选择框架',
    'selectOS': '选择操作系统',
    'installGuide': '安装指南',
    'downloadJava': '下载 Java',
    'alternativeSources': '替代源',
    'hideAlternatives': '隐藏替代',
    'loading': '加载中...',
    'tryAgain': '重试'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language') as Language;
    if (stored) return stored;
    
    const browserLang = navigator.language.split('-')[0] as Language;
    return ['en', 'ru', 'uk', 'de', 'ja', 'zh'].includes(browserLang) ? browserLang : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
